---
title: "Week7"
author: "nrupali shetty"
date: "7/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r setup, include=FALSE}
#Data Visualization-->grammar of graphics
#Installing package tidyverse and loading tidyverse
install.packages("tidyverse")
library(tidyverse)
```

```{r setup, include=TRUE}
#mpg dataframe using ggplot2 contains observations by the US Environmental Protection Agency on 38 models of car.
mpg
```



```{r setup, include=TRUE}
#Displ-->car engine size
#hwy-->fuel efficiency on highway

#learning to create ggplot to display x axis and hwy on y axis
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))


#using this code to make graphs with ggplot2
#ggplot(data = <DATA>) + 
#  <GEOM_FUNCTION>(mapping = aes(<MAPPINGS>))
```


```{r setup, include=TRUE}
#Aesthetic mappings two dimensional scatterplot by mapping to aesthetic include size shape object
#convey more information data plot to variables in dataset

#mapping the colors of points to the class variable to reveal the class of each car.
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))
```

```{r setup, include=TRUE}
#mapping the colors of points to the class variable to reveal the class of each car.
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, size = class))
```


```{r setup, include=TRUE}
#transparency of the points can be controlled by mapping alpha aesthetic and shape of the points can be controlled by shape aesthetic
#Graph1 Left
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))

#Graph2 Right
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))
#Additonal groups will go unplotted such a suv in ggplot2 when we use shape aesthetic
#aes() associates name of aesthetic with variabl to display
```

```{r setup, include=TRUE}
#To change all of the points in our plot blue:
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), color = "red")
#Level of aesthetics
#name of color as character string
#size of point in mm
#shape of point as number
``` 

```{r setup, include=TRUE}
#To split plot into facets displaying subset of data
#facet_wrap() creates variable name and is discrete
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ class, nrow = 2)
```
```{r setup, include=TRUE}
#facet_grid() is used to facet plot on combination of two variables
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(drv ~ cyl)
```

```{r setup, include=TRUE}

#Geom object plot uses to represent data
#geom in plot can be changed by changing the geom function added in the ggplot()
#displ1 left
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))

#displ2 right
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy))
```
```{r setup, include=TRUE}
#using geom_smooth single geometric object to display multiple rows of data
#group to draw multiple objects

ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))


```
```{r setup, include=TRUE}
#trying to map an aesthetic to discrete variable linetype
#displ1
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy))
#displ2              
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, group = drv))
#displ3
ggplot(data = mpg) +
  geom_smooth(
    mapping = aes(x = displ, y = hwy, color = drv),
    show.legend = FALSE
  )

#to display multiple geoms in same plot adding multiple geom functions to ggplot():
```

```{r setup, include=TRUE}
#Multiple geom functions can be added to display to display multiple geoms in same plot
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  geom_smooth(mapping = aes(x = displ, y = hwy))
```

```{r setup, include=TRUE}
#set of mappings can be passed to ggplot() to avoid reptition of changing code
#same plot generated as above
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth()
```
```{r setup, include=TRUE}
#To display different aesthetics in different layers
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) + 
  geom_smooth()
```
```{r setup, include=TRUE}
#To specify different data for each layer
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) + 
  geom_smooth(data = filter(mpg, class == "subcompact"), se = FALSE)
```

```{r setup, include=TRUE}
#basic bar chart with geom_bar() diamonds dataset including parameters like price,carat,color ,clarity
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut))

#we can use geoms and stats interchangeably using plot stat_count() 
```

```{r setup, include=TRUE}
#stat_count an be used instead of geom_bar(). Same bar graph is generated
ggplot(data = diamonds) + 
  stat_count(mapping = aes(x = cut))
```

```{r setup, include=TRUE}
#trying to change default stat to geom_bar() from count.

demo <- tribble(
  ~cut,         ~freq,
  "Fair",       1610,
  "Good",       4906,
  "Very Good",  12082,
  "Premium",    13791,
  "Ideal",      21551
)

ggplot(data = demo) +
  geom_bar(mapping = aes(x = cut, y = freq), stat = "identity")

#showing ideal cut higher in frequency than rest

```
```{r setup, include=TRUE}
#bar chart of proportion, rather than count
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, y = ..prop.., group = 1))

#variables computed by stat
```


```{r setup, include=TRUE}
#stat_summary used to summarises the y values for each unique x value-->drawing freater attention to statiscal tranformation
ggplot(data = diamonds) + 
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )

#it provides 20 stats each stat=function 
```

```{r setup, include=TRUE}

#Position adjustments--> association with bar charts color one of them aesthetically fill
#bar chart can be coloured using colour or fill

#displ1
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, colour = cut))

#displ2
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = cut))

#fill aesthetic clarity bars are stacked each colored rectaned shows cut and clarity
```

```{r setup, include=TRUE}
#combination of cut and clarity is represted by each coloured rectangle
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity))

#stacking is performed by position adjustment specified by position argument, three ways "identity","dodge" and "fill"
```

```{r setup, include=TRUE}
#position = "identity" will place each object exactly where it falls in the context of the graph.
#checking overlapping by making bars slightly transparent setting alpha to small value and complete transparent by settin fill=NA
#displ1
ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) + 
  geom_bar(alpha = 1/5, position = "identity")
#displ2
ggplot(data = diamonds, mapping = aes(x = cut, colour = clarity)) + 
  geom_bar(fill = NA, position = "identity")
```

```{r setup, include=TRUE}
#position = "fill" works like stacking making each set of stacked bars the same height.Comparing proportions acros groups
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "fill")
```

```{r setup, include=TRUE}
#position = "dodge" places overlapping objects directly beside one another. easier to compare values 

ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "dodge")

#these are uselful for scatterplots
```

```{r setup, include=TRUE}
#position = "jitter" to avoid gridding which adds small amt of ransom noise to each point 
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), position = "jitter")
```
```{r setup, include=TRUE}
#coord_flip() switches the x and y axes.for horizontal boxplots

ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot()
#with Coord_flip()
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot() +
  coord_flip()
```
```{r setup, include=TRUE}
#coord_quickmap() sets aspect ration for maps with ggplot2
nz <- map_data("nz")

ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", colour = "black")

ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", colour = "black") +
  coord_quickmap()
```

```{r setup, include=TRUE}
#coord_polar() uses polar coordinates connection bar chart and coxcomb chart
bar <- ggplot(data = diamonds) + 
  geom_bar(
    mapping = aes(x = cut, fill = cut), 
    show.legend = FALSE,
    width = 1
  ) + 
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)

#displ1
bar + coord_flip()
#displ2
bar + coord_polar()
#shows ideal spreadout wider
```